#!/usr/bin/env node

import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline";

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(query) {
  return new Promise((resolve) => rl.question(query, resolve));
}

function generateSecret() {
  return randomBytes(32).toString("hex");
}

function yellow(msg) {
  console.log(`\x1b[33m${msg}\x1b[0m`);
}

function green(msg) {
  console.log(`\x1b[32m${msg}\x1b[0m`);
}

async function confirm(query, defaultValue = "y") {
  const hint = defaultValue === "y" ? "Y/n" : "y/N";
  const answer = (await ask(`\n${query} (${hint}) `)).trim().toLowerCase();
  if (!answer) return defaultValue === "y";
  return answer === "y" || answer === "yes";
}

async function main() {
  console.log("\n  Selfie — Setup\n");

  const root = resolve(import.meta.dirname, "..");
  const serverEnvPath = resolve(root, "apps/server/.env");
  const clientEnvPath = resolve(root, "apps/client/.env");

  // Warn if env files already exist
  if (existsSync(serverEnvPath) || existsSync(clientEnvPath)) {
    yellow("Existing .env files detected. They will be overwritten.");
    const ok = await confirm("Continue?");
    if (!ok) {
      console.log("Aborted.");
      process.exit(0);
    }
  }

  // ── Domain ──────────────────────────────────────────────────────────
  let domain = "";
  const useDomain = await confirm(
    "Will you use a domain (e.g. yourdomain.xyz)?",
  );

  if (useDomain) {
    domain = (await ask("\nEnter your domain (e.g. yourdomain.xyz): ")).trim();
    while (!domain) {
      domain = (await ask("Domain cannot be empty: ")).trim();
    }
    if (!domain.startsWith(".")) domain = `.${domain}`;
    green(`  Using domain: ${domain}`);
  }

  // ── Secrets ─────────────────────────────────────────────────────────
  let cryptSecret = "";
  let jwtSecret = "";

  const customSecrets = await confirm(
    "Do you want to provide your own encryption secrets?",
  );

  if (customSecrets) {
    cryptSecret = (
      await ask("\nCrypt secret (used for password hashing): ")
    ).trim();
    while (!cryptSecret) {
      cryptSecret = (await ask("Crypt secret cannot be empty: ")).trim();
    }
    jwtSecret = (await ask("JWT secret (used for signing tokens): ")).trim();
    while (!jwtSecret) {
      jwtSecret = (await ask("JWT secret cannot be empty: ")).trim();
    }
  } else {
    cryptSecret = generateSecret();
    jwtSecret = generateSecret();
    green("\n  Generated random secrets.");
  }

  // ── Ports ───────────────────────────────────────────────────────────
  const serverPort =
    (await ask("\nServer port (default 3001): ")).trim() || "3001";
  const clientPort =
    (await ask("Client port (default 3000): ")).trim() || "3000";

  // ── Cloudflare Tunnel ──────────────────────────────────────────────
  let setupTunnel = false;
  let tunnelName = "";

  if (useDomain) {
    setupTunnel = await confirm("Do you want to setup a Cloudflare tunnel?");

    if (setupTunnel) {
      tunnelName =
        (await ask("\nTunnel name (default: selfie): ")).trim() || "selfie";
      green(`  Tunnel name: ${tunnelName}`);
    }
  }

  // ── Write .env files ──────────────────────────────────────────────

  // Server .env
  const serverEnv = `# Selfie server configuration — generated by setup script

DATABASE_URL="postgresql://<user>:<password>@<host>:5432/<dbname>?schema=public"
CRYPT_SECRET="${cryptSecret}"
JWT_SECRET="${jwtSecret}"
NODE_ENV="production"
DOMAIN="${domain}"
PORT=${serverPort}
`;

  // Client .env
  const apiUrl = domain
    ? `https://selfie-api${domain}`
    : `http://localhost:${serverPort}`;

  const clientEnv = `# Selfie client configuration — generated by setup script

NEXT_PUBLIC_API_URL="${apiUrl}"
`;

  writeFileSync(serverEnvPath, serverEnv);
  writeFileSync(clientEnvPath, clientEnv);

  green("\n  .env files created successfully!");
  console.log(`    ${serverEnvPath}`);
  console.log(`    ${clientEnvPath}`);

  // ── Post-setup instructions ─────────────────────────────────────────
  console.log("\n── Next steps ──\n");

  if (setupTunnel) {
    const rawDomain = domain.replace(/^\./, "");

    console.log("\n  Setting up Cloudflare tunnel...\n");

    try {
      console.log("  Logging in to Cloudflare...");
      execSync("cloudflared tunnel login", { stdio: "inherit" });

      console.log(`  Creating tunnel '${tunnelName}'...`);
      const createOutput = execSync(`cloudflared tunnel create ${tunnelName}`, {
        encoding: "utf-8",
      });

      const idMatch = createOutput.match(
        /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i,
      );
      const tunnelId = idMatch?.[0] ?? "";

      if (tunnelId) {
        console.log(`  Tunnel ID: ${tunnelId}`);

        const config = [
          `tunnel: ${tunnelId}`,
          "",
          "ingress:",
          `  - hostname: selfie.${rawDomain}`,
          "    service: http://localhost:3000",
          "",
          `  - hostname: selfie-api.${rawDomain}`,
          "    service: http://localhost:3001",
          "",
          "  - service: http_status:404",
        ].join("\n");

        const configPath = resolve(root, "cloudflared_config.yml");
        writeFileSync(configPath, config);
        green(`  Tunnel config written: ${configPath}`);
      }

      console.log(`  Routing selfie.${rawDomain}...`);
      execSync(
        `cloudflared tunnel route dns ${tunnelName} selfie.${rawDomain}`,
        { stdio: "inherit" },
      );

      console.log(`  Routing selfie-api.${rawDomain}...`);
      execSync(
        `cloudflared tunnel route dns ${tunnelName} selfie-api.${rawDomain}`,
        { stdio: "inherit" },
      );

      green("\n  Tunnel created and configured!");

      console.log("\n  Start the tunnel with:");
      console.log(`    pnpm tunnel`);
    } catch (err) {
      console.error("\n  Tunnel setup failed:", err.message);
    }
  }

  console.log("\n  Database:");
  console.log("    1. Set DATABASE_URL in apps/server/.env");
  console.log(
    "    2. cd apps/server && pnpm exec prisma migrate dev --name init",
  );
  console.log("    3. cd apps/server && pnpm exec prisma generate");
  console.log("");

  rl.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
